set -g default-terminal "screen"
set -g base-index 0
setw -g pane-base-index 0

set -g status-keys emacs
set -g mode-keys emacs

unbind C-b
set -g prefix C-a

bind -N "Send the prefix key through to the application" \
    C-a send-prefix

set -g mouse on 
set -g focus-events off 
setw -g aggressive-resize off 
setw -g clock-mode-style 12
set -s escape-time 120 
set -g history-limit 10000

bind C-j display-popup -E "tms switch"
bind C-o display-popup -E "tms"
set-option -g status-position top
