animations {
    bezier=myBezier, 0.05, 0.9, 01, 1.05
    animation=windows, 1, 7, myBezier 
    animation=windowsOut, 1, 7, default, popin 80%
    animation=border, 1, 10, default 
    animation=borderangle, 1, 8, default 
    animation=fade, 1, 7, default 
    animation=workspaces, 1, 6, default 
    animation=layers, 1, 3, default, fade 
    enabled = true
}

decoration {
    blur {
        enabled = true
        ignore_opacity = false
        new_optimizations = true
        passes=4
        size=3
        xray=true
    }
    shadow {
        color=rgba(20202099)
    }
    rounding=24
}

dwindle {
    preserve_split=true
    pseudotile=true
}

general {
    border_size=2
    col.active_border=rgb(7daea3)
    col.inactive_border=rgb(5a524c)
    gaps_in=5
    gaps_out=15
}

gesture=3, horizontal, workspace 
gesture=4, horizontal, workspace 

group {
    groupbar {
        col.active=rgb(7daea3)
        col.inactive=rgb(5a524c)
        text_color=rgb(89b482)
    }
    col.border_active=rgb(7daea3)
    col.border_inactive=rgb(5a524c)
    col.border_locked_active=rgb(89b482)
}

input {
    touchpad {
        natural_scroll=true
        scroll_factor=0.3 
    }
    float_switch_override_focus=false 
    follow_mouse=2
    kb_layout=us
    natural_scroll=false 
    numlock_by_default=true 
}

layerrule=blur on, match:namespace ^shell:
layerrule=xray on, match:namespace ^shell:
layerrule=animation slidevert, match:namespace ^shell:

misc {
    background_color=rgb(202020)
    disable_hyprland_logo=true 
    middle_click_paste=false 
}

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bind = SUPER, 1, moveworkspacetomonitor, 1 current
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, moveworkspacetomonitor, 2 current
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, moveworkspacetomonitor, 3 current
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, moveworkspacetomonitor, 4 current
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, moveworkspacetomonitor, 5 current
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, moveworkspacetomonitor, 6 current
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, moveworkspacetomonitor, 7 current
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, moveworkspacetomonitor, 8 current
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, moveworkspacetomonitor, 9 current
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, moveworkspacetomonitor, 10 current
bind = SUPER, 0, workspace, 10

bind = SUPER, P, exec, kappashell-desktop popup open runner bottom
bind = SUPER, return, exec, kitty 
bind = SUPER, W, exec, firefox
bind = SUPER, N, exec, nautilus
bind = SUPER, C, killactive
bind = SUPER, V, togglefloating
bind = SUPER, J, togglesplit 
bind = SUPER, F, fullscreen 

bind = SUPER, left, movefocus, l 
bind = SUPER, right, movefocus, r 
bind = SUPER, up, movefocus, u 
bind = SUPER, down, movefocus, d 
